src/MVCData-Group5/Controllers/CartController.cs
using MVCData_Group5.Models;
using MVCData_Group5.Models.Database;
using MVCData_Group5.Models.ViewModels;
using MVCData_Group5.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCData_Group5.Controllers
{
    [ShoppingCartAsSessionActionFilter]
    public class CartController : MovieDbController
    {
        class ShoppingCartAsCookieActionFilter : ActionFilterAttribute
        {
            public override void OnActionExecuting(ActionExecutingContext filterContext)
            {
                var cartCookie = filterContext.HttpContext.Request.Cookies[DataKeys.ShoppingCart];
                if (cartCookie == null)
                {
                    ((CartController)filterContext.Controller).ShoppingCart = new ShoppingCart();
                }
                else
                {
                    try
                    {
                        ((CartController)filterContext.Controller).ShoppingCart = ShoppingCart.Deserialize(cartCookie.Value);
                    }
                    catch
                    {
                        ((CartController)filterContext.Controller).ShoppingCart = new ShoppingCart();
                    }
                }
            }

            public override void OnActionExecuted(ActionExecutedContext filterContext)
            {
                var cookie = new HttpCookie(DataKeys.ShoppingCart, ((CartController)filterContext.Controller).ShoppingCart.Serialize());
                cookie.Expires = DateTime.Now.AddDays(7);
                filterContext.HttpContext.Response.Cookies.Add(cookie);
            }
        }
        class ShoppingCartAsSessionActionFilter : ActionFilterAttribute
        {
            public override void OnActionExecuting(ActionExecutingContext filterContext)
            {
                var cart = ((Controller)filterContext.Controller).Session[DataKeys.ShoppingCart] as ShoppingCart;
                if(cart == null)
                {
                    cart = new ShoppingCart();
                    ((Controller)filterContext.Controller).Session[DataKeys.ShoppingCart] = cart;
                }
                ((CartController)filterContext.Controller).ShoppingCart = cart;
            }
        }

        public ShoppingCart ShoppingCart { get; set; }

        protected double ShoppingCartTotal
        {
            get
            {
                object total = Session[DataKeys.ShoppingCartTotal];
                if (total is double)
                {
                    return (double)total;
                }
                Session[DataKeys.ShoppingCartTotal] = 0D;
                return 0D;
            }
            set
            {
                Session[DataKeys.ShoppingCartTotal] = value;
            }
        }

        protected double UpdateShoppingCartTotal(IEnumerable<Movie> movies = null)
        {
            var movieIds = ShoppingCart.Keys.Where(k => ShoppingCart[k] > 0).ToArray();
            if (movies == null || movieIds.Except(movies.Select(m => m.Id)).Count() > 0)
            {
                movies = db.Movies.Where(m => movieIds.Contains(m.Id)).ToList();
            }

            double total = movies.Sum(m => m.Price * ShoppingCart[m.Id]);
            ShoppingCartTotal = total;
            return total;
        }

        [ChildActionOnly]
        public ActionResult NavBarCartDisplay()
        {
            if(ShoppingCart.AmountItems > 0 && ShoppingCartTotal == 0)
            {
                UpdateShoppingCartTotal();
            }

            ViewBag.AmountItems = ShoppingCart.AmountItems;
            ViewBag.OrderTotal = ShoppingCartTotal;

            return PartialView("_NavBarCartDisplayPartial");
        }

        [HttpPost]
        public ActionResult AddToCart(int movieId, string returnUrl)
        {
            Movie movie = db.Movies.Find(movieId);
            if (movie != null)
            {
                ShoppingCart.Add(movieId);
                ShoppingCartTotal += movie.Price;
            }
            else
            {
                Messages.NewDanger("Failed to add movie to shopping cart!");
            }

            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                return RedirectToAction("Index", "Movie");
            }
        }

        public ActionResult Index()
        {
            var movieIds = ShoppingCart.Keys.Where(k => ShoppingCart[k] > 0).ToArray();

            IQueryable<Movie> query = db.Movies
                .Where(m => movieIds.Contains(m.Id));
            ViewBag.Query = query.ToString();

            List<Movie> movies = query.ToList();
            var movieVMs = movies.Select(m => new ShoppingCartMovieViewModel
            {
                Id = m.Id,
                Title = m.Title,
                Price = m.Price,
                Amount = ShoppingCart[m.Id]
            });

            var model = new ShoppingCartViewModel
            {
                Movies = movieVMs.ToList(),
                MovieCount = ShoppingCart.AmountItems,
                OrderTotal = UpdateShoppingCartTotal(movies)
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult ModifyAmount(int id, int amount)
        {
            if (ShoppingCart.Keys.Contains(id) && amount >= 0)
            {
                ShoppingCart[id] = amount;
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult EmptyCart()
        {
            ShoppingCart.Clear();

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult ReduceAllByOne()
        {
            ShoppingCart.RemoveOneOfAll();

            return RedirectToAction("Index");
        }

        [ChildActionOnly]
        public ActionResult CheckOutButtons(CheckOutViewModel model)
        {
            return PartialView("_CheckOutButtonsPartial", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("CheckOut")]
        public ActionResult CheckOutSubmit(CheckOutViewModel model)
        {
            if (ShoppingCart.AmountItems == 0)
            {
                Messages.NewInfo("You can't check out an empty order.");
                return RedirectToAction("Index", model);
            }

            if (ModelState.IsValid)
            {
                Customer customer = db.Customers.FirstOrDefault(c => c.EmailAddress == model.EmailAddress);
                if (customer == null)
                {
                    // Error handling
                    Messages.NewDanger("No details found for the specified email address!");
                }

                if (customer != null && CheckOut(customer))
                {
                    return RedirectToAction("CheckOutComplete");
                }
            }

            return RedirectToAction("Index", model);
        }

        [ChildActionOnly]
        public ActionResult CheckOutOrderDetails()
        {
            var model = new CheckOutOrderDetailsViewModel
            {
                MovieCount = ShoppingCart.AmountItems,
                OrderTotal = UpdateShoppingCartTotal()
            };

            return PartialView("_CheckOutOrderDetailsPartial", model);
        }

        public ActionResult CheckOutNewCustomer()
        {
            if (ShoppingCart.AmountItems == 0)
            {
                Messages.NewInfo("You can't check out an empty order.");
                return RedirectToAction("Index");
            }

            var model = new CheckOutNewUserViewModel();
            if (Request.IsAuthenticated)
            {
                ApplicationUser user = GetLoggedInUser();
                if (user.Customer != null)
                {
                    return RedirectToAction("Index");
                }
                model.EmailAddress = user.Email;
            }
            ModelState.Clear();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("CheckOutNewCustomer")]
        public ActionResult CheckOutNewCustomerSubmit(CheckOutNewUserViewModel model)
        {
            if (ShoppingCart.AmountItems == 0)
            {
                Messages.NewInfo("You can't check out an empty order.");
                return RedirectToAction("Index");
            }

            if (ModelState.IsValid)
            {
                Customer customer = new Customer
                {
                    Firstname = model.Firstname,
                    Lastname = model.Lastname,
                    DeliveryAddress = model.DeliveryAddress,
                    DeliveryCity = model.DeliveryCity,
                    DeliveryZip = model.DeliveryZip,
                    EmailAddress = model.EmailAddress,
                    PhoneNo = model.PhoneNo
                };

                if (model.SameBillingAsDelivery)
                {
                    customer.BillingAddress = model.DeliveryAddress;
                    customer.BillingCity = model.DeliveryCity;
                    customer.BillingZip = model.DeliveryZip;
                }
                else
                {
                    customer.BillingAddress = model.BillingAddress;
                    customer.BillingCity = model.BillingCity;
                    customer.BillingZip = model.BillingZip;
                }

                if (Request.IsAuthenticated)
                {
                    ApplicationUser user = GetLoggedInUser();
                    user.Customer = customer;
                    db.SaveChanges();
                }

                if (CheckOut(customer))
                {
                    return RedirectToAction("CheckOutComplete");
                }
            }

            return View(model);
        }

        [Authorize]

src/MVCData-Group5/Controllers/CustomerController.cs
using MVCData_Group5.Models.ViewModels;
using MVCData_Group5.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCData_Group5.Controllers
{
    public class CustomerController : MovieDbController
    {
        // GET: Order
        public ActionResult Index()
        {
            if(Request.IsAuthenticated)
            {
                string email = GetLoggedInUser()?.Customer?.EmailAddress;
                if (email != null)
                    return RedirectToAction("Orders", new { email });
            }
            ViewBag.CustomerSL = new SelectList(db.Customers, "EmailAddress", "EmailAddress");
            return View();
        }

        public ActionResult Orders(string email)
        {
            if(email == null)
            {
                return RedirectToAction("Index");
            }

            Models.Database.Customer customer = db.Customers.FirstOrDefault(c => c.EmailAddress == email);

            if(customer == null)
            {
                return RedirectToAction("Index");
            }

            var query = customer.Orders.Select(o => new CustomerOrderViewModel
            {
                OrderDate = o.OrderDate,
                Movies = o.OrderRows.GroupBy(r => r.Movie).Select(g => new ShoppingCartMovieViewModel
                {
                    Id = g.Key.Id,
                    Title = g.Key.Title,
                    Price = g.First().Price,
                    Amount = g.Count()
                }).ToList(),
                TotalCost = o.OrderRows.Sum(r => r.Price),
                MovieCount = o.OrderRows.Count()
            });

            var model = new CustomerOrdersViewModel
            {
                Name = string.Format("{0} {1}", customer.Firstname, customer.Lastname),
                EmailAddress = customer.EmailAddress,
                Orders = query.ToList()
            };

            return View(model);
        }

        [ChildActionOnly]
        public ActionResult MostExpensiveOrder()
        {
            var order = db.Orders.OrderByDescending(o => o.OrderRows.Sum(r => r.Price)).FirstOrDefault();
            if(order == null)
            {
                return PartialView("_SingleOrderSummaryPartial", new OrderSummaryViewModel());
            }

            var model = new OrderSummaryViewModel
            {
                OrderDate = order.OrderDate,
                TotalCost = order.OrderRows.Sum(r => r.Price),
                MovieCount = order.OrderRows.Count(),
                Name = $"{order.Customer.Firstname} {order.Customer.Lastname}"
            };

            return PartialView("_SingleOrderSummaryPartial", model);
        }
    }
}

src/MVCData-Group5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Movie Store", "Index", "Movie", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Movie")</li>
                    <li>@Html.ActionLink("Browse Movies", "List", "Movie")</li>
                    <li>@Html.ActionLink("Add Movie", "Add", "Movie")</li>
                    <li>@Html.ActionLink("View Orders", "Index", "Customer")</li>
                </ul>
                @Html.Partial("_LoginPartial")
                @Html.Action("NavBarCartDisplay", "Cart")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @Html.Action("ViewMessages", "Movie")
        @RenderBody()
    </div>
    <div class="container">
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Martin Johansson</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

src/MVCData-Group5/Views/Shared/_ViewMessagesPartial.cshtml
@model IEnumerable<MVCData_Group5.Utilities.Message>


@foreach (var item in Model) {
    <div class="alert alert-@item.Type.ToString().ToLower() alert-dismissable" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Html.Raw(item.Text)
    </div>
}

src/MVCData-Group5/Views/Shared/_movieRowPartial.cshtml
@model MVCData_Group5.Models.ViewModels.DisplayMovieViewModel

<div class="col-md-4">
    @if (!string.IsNullOrEmpty(Model.ImageUrl))
    {
        <img src="@Model.ImageUrl" height="50" width="50" />
    }
    <dl class="dl-vertical">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Director)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Director)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>

    @using (Html.BeginForm(new { controller = "Cart", action = "AddToCart" }))
    {
        @Html.Hidden("movieId", Model.Id)
        <input type="submit" name="addToCart" value="Add to Cart" />
    }
</div>