src/MVCData-Group5/Models/Database/Movie.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MVCData_Group5.Models.Database
{
    public class Movie
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [MaxLength(250)]
        public string Title { get; set; }

        [Required]
        [MaxLength(250)]
        public string Director { get; set; }

        [Required]
        public int ReleaseYear { get; set; }

        [DataType(DataType.ImageUrl)]
        public string ImageUrl { get; set; }

        [Required]
        [DataType(DataType.Currency)]
        public double Price { get; set; }

        public virtual ICollection<OrderRow> OrderRows { get; set; }
    }
}

src/MVCData-Group5/Models/ViewModels/CheckOutViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MVCData_Group5.Models.ViewModels
{
    public class CheckOutViewModel
    {
        [EmailAddress]
        [Required]
        [Display(Name = "Email Address")]
        public string EmailAddress { get; set; }
    }
}

src/MVCData-Group5/Models/ViewModels/MovieViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVCData_Group5.Models.ViewModels
{
    public class CreateMovieViewModel
    {
        [Required]
        [MaxLength(250)]
        public string Title { get; set; }

        [Required]
        [MaxLength(250)]
        public string Director { get; set; }

        [Required]
        [Range(1900, 9999)]
        [Display(Name = "Release Year")]
        public int ReleaseYear { get; set; }

        [DataType(DataType.ImageUrl)]
        [Url]
        [Display(Name = "Image URL")]
        public string ImageUrl { get; set; }

        [Required]
        [DataType(DataType.Currency)]
        public double Price { get; set; }
    }
    public class DisplayMovieViewModel
    {
        public int Id { get; set; }

        [Required]
        [MaxLength(250)]
        public string Title { get; set; }

        [Required]
        [MaxLength(250)]
        public string Director { get; set; }

        [Required]
        [Range(1900, 9999)]
        [Display(Name = "Release Year")]
        public int ReleaseYear { get; set; }

        [DataType(DataType.ImageUrl)]
        [Url]
        [Display(Name = "Image")]
        public string ImageUrl { get; set; }

        [Required]
        [DataType(DataType.Currency)]
        public double Price { get; set; }
    }

    public class ShoppingCartMovieViewModel
    {
        [Required]
        [MaxLength(250)]
        public string Title { get; set; }

        [Required]
        [DataType(DataType.Currency)]
        public double Price { get; set; }

        [Display(Name = "Amount")]
        public int Amount { get; set; }
        public int Id { get; set; }
    }
}

src/MVCData-Group5/Controllers/CustomerController.cs
using MVCData_Group5.Models.ViewModels;
using MVCData_Group5.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCData_Group5.Controllers
{
    public class CustomerController : MovieDbController
    {
        // GET: Order
        public ActionResult Index()
        {
            if(Request.IsAuthenticated)
            {
                string email = GetLoggedInUser()?.Customer?.EmailAddress;
                if (email != null)
                    return RedirectToAction("Orders", new { email });
            }
            ViewBag.CustomerSL = new SelectList(db.Customers, "EmailAddress", "EmailAddress");
            return View();
        }

        public ActionResult Orders(string email)
        {
            if(email == null)
            {
                return RedirectToAction("Index");
            }

            Models.Database.Customer customer = db.Customers.FirstOrDefault(c => c.EmailAddress == email);

            if(customer == null)
            {
                return RedirectToAction("Index");
            }

            var query = customer.Orders.Select(o => new CustomerOrderViewModel
            {
                OrderDate = o.OrderDate,
                Movies = o.OrderRows.GroupBy(r => r.Movie).Select(g => new ShoppingCartMovieViewModel
                {
                    Id = g.Key.Id,
                    Title = g.Key.Title,
                    Price = g.First().Price,
                    Amount = g.Count()
                }).ToList(),
                TotalCost = o.OrderRows.Sum(r => r.Price),
                MovieCount = o.OrderRows.Count()
            });

            var model = new CustomerOrdersViewModel
            {
                Name = string.Format("{0} {1}", customer.Firstname, customer.Lastname),
                EmailAddress = customer.EmailAddress,
                Orders = query.ToList()
            };

            return View(model);
        }

        [ChildActionOnly]
        public ActionResult MostExpensiveOrder()
        {
            var order = db.Orders.OrderByDescending(o => o.OrderRows.Sum(r => r.Price)).FirstOrDefault();
            if(order == null)
            {
                return PartialView("_SingleOrderSummaryPartial", new OrderSummaryViewModel());
            }

            var model = new OrderSummaryViewModel
            {
                OrderDate = order.OrderDate,
                TotalCost = order.OrderRows.Sum(r => r.Price),
                MovieCount = order.OrderRows.Count(),
                Name = $"{order.Customer.Firstname} {order.Customer.Lastname}"
            };

            return PartialView("_SingleOrderSummaryPartial", model);
        }
    }
}

src/MVCData-Group5/Controllers/MovieController.cs
using MVCData_Group5.Models;
using MVCData_Group5.Models.Database;
using MVCData_Group5.Models.ViewModels;
using MVCData_Group5.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCData_Group5.Controllers
{
    public class MovieController : MovieDbController
    {
        private const int MOVIES_PER_PAGE_DEFAULT = 9;

        public ActionResult Index()
        {
            return View();
        }

        [ChildActionOnly]
        public ActionResult ViewMessages()
        {
            var model = Messages.GetAll();
            return PartialView("_ViewMessagesPartial", model);
        }

        // GET: Movie
        public ActionResult List(string filter, int length = MOVIES_PER_PAGE_DEFAULT, int page = 1)
        {
            // Decrement page for easier calculations, but not less than 0
            page = --page < 0 ? 0 : page;
            // Ensure length is positive
            length = length > 0 ? length : MOVIES_PER_PAGE_DEFAULT;
            
            IQueryable<Movie> query = db.Movies;

            if (!string.IsNullOrWhiteSpace(filter))
            {
                query = query.Where(m => m.Title.Contains(filter));
                ViewBag.Filter = filter;
            }
            ViewBag.Pages = (query.Count() + length - 1) / length;

            var model = query.OrderBy(m => m.Title.ToLower()).Skip(length * page).Take(length).Select(m => new DisplayMovieViewModel
            {
                Id = m.Id,
                Title = m.Title,
                Director = m.Director,
                Price = m.Price,
                ReleaseYear = m.ReleaseYear,
                ImageUrl = m.ImageUrl
            });

            ViewBag.CurrentPage = page + 1;
            // Hides length from url if it is the default value
            if (length != MOVIES_PER_PAGE_DEFAULT)
                ViewBag.Length = length;

            return View(model.ToList());
        }

        [ChildActionOnly]
        public ActionResult MovieEntry(DisplayMovieViewModel model)
        {
            ViewBag.ReturnUrl = Request.Url.PathAndQuery;

            return PartialView("_MovieTilePartial", model);
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(CreateMovieViewModel movie)
        {
            if (ModelState.IsValid)
            {
                Movie m = new Movie
                {
                    Title = movie.Title,
                    Director = movie.Director,
                    ReleaseYear = movie.ReleaseYear,
                    Price = movie.Price,
                    ImageUrl = movie.ImageUrl
                };
                db.Movies.Add(m);
                db.SaveChanges();

                Messages.NewSuccess($"<em>{movie.Title}</em> was added.");

                return RedirectToAction("Add");
            }

            return View(movie);
        }

        public ActionResult PopularMovies(int count = 5)
        {
            count = count < 1 ? 1 : count;

            var model = db.Movies.OrderByDescending(m => m.OrderRows.Count()).Take(count).Select(m => new DisplayMovieViewModel
            {
                Id = m.Id,
                Title = m.Title,
                Director = m.Director,
                Price = m.Price,
                ReleaseYear = m.ReleaseYear,
                ImageUrl = m.ImageUrl
            });

            return PartialView("_MultipleMoviesPartial", model.ToList());
        }

        public ActionResult NewestMovies(int count = 5)
        {
            count = count < 1 ? 1 : count;

            var model = db.Movies.OrderByDescending(m => m.ReleaseYear).Take(count).Select(m => new DisplayMovieViewModel
            {
                Id = m.Id,
                Title = m.Title,
                Director = m.Director,
                Price = m.Price,
                ReleaseYear = m.ReleaseYear,
                ImageUrl = m.ImageUrl
            });

            return PartialView("_MultipleMoviesPartial", model.ToList());
        }

        public ActionResult OldestMovies(int count = 5)
        {
            count = count < 1 ? 1 : count;

            var model = db.Movies.OrderBy(m => m.ReleaseYear).Take(count).Select(m => new DisplayMovieViewModel
            {
                Id = m.Id,
                Title = m.Title,
                Director = m.Director,
                Price = m.Price,
                ReleaseYear = m.ReleaseYear,
                ImageUrl = m.ImageUrl
            });

            return PartialView("_MultipleMoviesPartial", model.ToList());
        }

        public ActionResult CheapestMovies(int count = 5)
        {
            count = count < 1 ? 1 : count;

            var model = db.Movies.OrderBy(m => m.Price).Take(count).Select(m => new DisplayMovieViewModel
            {
                Id = m.Id,
                Title = m.Title,
                Director = m.Director,
                Price = m.Price,
                ReleaseYear = m.ReleaseYear,
                ImageUrl = m.ImageUrl
            });

            return PartialView("_MultipleMoviesPartial", model.ToList());
        }
    }
}

src/MVCData-Group5/Views/Movie/Add.cshtml
@using MVCData_Group5.Utilities
@model MVCData_Group5.Models.ViewModels.CreateMovieViewModel

@{
    ViewBag.Title = "Add Movie";
}

<div class="col-md-6 col-md-offset-2">
    <h2>Add Movie</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Director, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Director, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Director, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ReleaseYear, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ReleaseYear, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ReleaseYear, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-success" />
                    @Html.ActionLink("Cancel", "Index", "Movie", null, new { @class="btn btn-danger"})
                </div>
            </div>
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/MVCData-Group5/Views/Movie/Cart.cshtml
@model IEnumerable<MVCData_Group5.Models.ViewModels.ShoppingCartMovieViewModel>

@{
    ViewBag.Title = "Cart";
}

<h2>Cart</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AmountInCart)
            </th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <td><strong>Total</strong></td>
            <td>@ViewBag.OrderTotal.ToString("C")</td>
            <td>@ViewBag.MovieCount</td>
        </tr>
    </tfoot>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AmountInCart)
                </td>
            </tr>
        }
    </tbody>

</table>

@using (Html.BeginForm("ReduceAllByOne", "Movie"))
{
    <input type="submit" name="reduceAll" value="Remove one of all movies" />
}

@Html.ActionLink("Check out", "CheckOut", null, new { @class = "btn btn-default"})

<pre class="hidden">
@ViewBag.Query
</pre>

src/MVCData-Group5/Views/Movie/CheckOut.cshtml
@model MVCData_Group5.Models.ViewModels.CheckOutViewModel

@{
    ViewBag.Title = "CheckOut";
}

<h2>CheckOut</h2>

<div>

    <h4>OrderUserViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MovieCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MovieCount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OrderTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderTotal)
        </dd>

    </dl>
    @using (Html.BeginForm())
    {
        @Html.EditorFor(model => model.EmailAddress)
        <input type="submit" name="checkoutexisting" value="Check out" />
    }
    @Html.ActionLink("Check out as new customer", "CheckOutNewCustomer", null, new { @class="btn btn-default"})
</div>
<p>
    @Html.ActionLink("Back to Cart", "Cart")
</p>

src/MVCData-Group5/Views/Movie/CheckOutNewCustomer.cshtml
@model MVCData_Group5.Models.ViewModels.NewUserViewModel

@{
    ViewBag.Title = "CheckOutNewCustomer";
}

<h2>CheckOutNewCustomer</h2>

<dl class="dl-horizontal">
    <dt>
        Amount Movies
    </dt>

    <dd>
        @ViewBag.MovieCount
    </dd>
    <dt>
        Order Total
    </dt>

    <dd>
        @ViewBag.OrderTotal.ToString("C")
    </dd>

</dl>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>NewUserViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Firstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Firstname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Firstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lastname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lastname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lastname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeliveryAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeliveryAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeliveryAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeliveryCity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeliveryCity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeliveryCity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeliveryZip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeliveryZip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeliveryZip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SameBillingAsDelivery, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.SameBillingAsDelivery)
                    @Html.ValidationMessageFor(model => model.SameBillingAsDelivery, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BillingAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BillingAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BillingAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BillingCity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BillingCity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BillingCity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BillingZip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BillingZip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BillingZip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Check Out" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Cart", "Cart")
</div>

src/MVCData-Group5/Views/Movie/Index.cshtml
@{
    ViewBag.Title = "Front";
}

<h2>Front</h2>

<h3>Popular Movies</h3>
@Html.Action("PopularMovies")
<hr />
<h3>Newest Movies</h3>
@Html.Action("NewestMovies")
<hr />
<h3>Oldest Movies</h3>
@Html.Action("OldestMovies")
<hr />
<h3>Cheapest Movies</h3>

@Html.Action("CheapestMovies")
<hr />
<h3>Most Expensive Order</h3>

<div class="row">
    @Html.Action("MostExpensiveOrder", "Customer")
</div>

src/MVCData-Group5/Views/Movie/List.cshtml
@model IEnumerable<MVCData_Group5.Models.ViewModels.DisplayMovieViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Browse Movies</h2>

<div class="row">

    <div class="col-lg-4">
        @using (Html.BeginForm("List", "Movie", null, FormMethod.Get, null))
        {
            <input type="hidden" name="length" value="@ViewBag.Length" />
            <div class="form-group">
                <div class="input-group">
                    <input type="search" name="filter" placeholder="Type text to search..." class="form-control" value="@ViewBag.Filter" autofocus />
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">Go!</button>
                    </span>
                </div>
            </div>
        }
    </div>
</div>

@Html.Partial("_MultipleMoviesPartial", Model)

<div class="row">
    <nav aria-label="Page navigation">
        <ul class="pagination">
            @if (ViewBag.CurrentPage == 1)
            {
                <li class="disabled">
                    <a>«</a>
                </li>
            }
            else
            {
                <li>
                    @Html.ActionLink("«", "List", new { page = (ViewBag.CurrentPage - 1), length = ViewBag.Length, filter = ViewBag.Filter })
                </li>
            }
            @for (int i = 1; i <= ViewBag.Pages; i++)
            {
                <li class="@(i == ViewBag.CurrentPage ? "active" : "")">
                    @Html.ActionLink(i.ToString(), "List", new { page = i, length = ViewBag.Length, filter = ViewBag.Filter })
                </li>
            }
            @if (ViewBag.CurrentPage == ViewBag.Pages)
            {
                <li class="disabled">
                    <a>»</a>
                </li>
            }
            else
            {
                <li>
                    @Html.ActionLink("»", "List", new { page = (ViewBag.CurrentPage + 1), length = ViewBag.Length, filter = ViewBag.Filter })
                </li>
            }
        </ul>
    </nav>
</div>

src/MVCData-Group5/Views/Movie/MultipleMovies.cshtml
@model IEnumerable<MVCData_Group5.Models.ViewModels.DisplayMovieViewModel>

<div class="row">
    @foreach (var movie in Model)
    {
        Html.RenderAction("MovieEntry", movie);
    }
</div>

src/MVCData-Group5/Views/Movie/_MovieTilePartial.cshtml
@model MVCData_Group5.Models.ViewModels.DisplayMovieViewModel

<div class="col-md-4">
    <div class="thumbnail">
        <img src="@(string.IsNullOrEmpty(Model.ImageUrl) ? "http://via.placeholder.com/182x268?text=NO%20PICTURE" : Model.ImageUrl)" height="268" width="182" class="img-rounded" />
        <div class="caption">
            
            <h3 style="min-height:2.5em;">@Html.DisplayFor(model => model.Title)</h3>

            <dl class="dl-horizontal">
                <dt>@Html.DisplayNameFor(model => model.ReleaseYear)</dt>
                <dd>@Html.DisplayFor(model => model.ReleaseYear)</dd>
                <dt>@Html.DisplayNameFor(model => model.Director)</dt>
                <dd>@Html.DisplayFor(model => model.Director)</dd>
        </dl>

            <div class="text-right">
                @using (Html.BeginForm("AddToCart", "Cart", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-inline" }))
                {
                    @Html.Hidden("movieId", Model.Id)
                    <p class="lead">
                        @Html.DisplayFor(model => model.Price)
                        <button type="submit" class="btn btn-success">Add to Cart</button>
                    </p>
                }


            </div>
        </div>
    </div>
</div>

src/MVCData-Group5/Views/Movie/_MultipleMoviesPartial.cshtml
@model IEnumerable<MVCData_Group5.Models.ViewModels.DisplayMovieViewModel>

<div class="row">
    @foreach (var movie in Model)
    {
        Html.RenderAction("MovieEntry", movie);
    }
</div>

src/MVCData-Group5/Views/Movie/_movieRowPartial.cshtml
@model MVCData_Group5.Models.ViewModels.DisplayMovieViewModel

<div class="col-md-4">
    <div class="thumbnail">
        <img src="@(string.IsNullOrEmpty(Model.ImageUrl) ? "http://via.placeholder.com/182x268?text=NO%20PICTURE" : Model.ImageUrl)" height="268" width="182" class="img-rounded" />
        <div class="caption">
            
            <h3 style="min-height:2.5em;">@Html.DisplayFor(model => model.Title)</h3>

            <dl class="dl-horizontal">
                <dt>@Html.DisplayNameFor(model => model.ReleaseYear)</dt>
                <dd>@Html.DisplayFor(model => model.ReleaseYear)</dd>
                <dt>@Html.DisplayNameFor(model => model.Director)</dt>
                <dd>@Html.DisplayFor(model => model.Director)</dd>
        </dl>

            <div class="text-right">
                @using (Html.BeginForm("AddToCart", "Cart", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-inline" }))
                {
                    @Html.Hidden("movieId", Model.Id)
                    <p class="lead">
                        @Html.DisplayFor(model => model.Price)
                        <button type="submit" class="btn btn-success">Add to Cart</button>
                    </p>
                }


            </div>
        </div>
    </div>
</div>